version: '3.8'
services:
  db:
    image: postgres:15
    container_name: cardapio_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cardapio_pwa
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: cardapio_cache
    ports:
      - "6379:6379"